config/routes.rb
IpcPcMgmt::Application.routes.draw do

  match 'warriors/list' => 'warriors#list'
  match 'sessions/list' => 'sessions#list'
  match 'sessions/end_session'=>'sessions#end_session'
  match 'sessions/warrior_sessions'=>'sessions#warrior_sessions'
  match 'sessions/statistics'=> 'sessions#statistics'
  match 'warriors/regional_stats'=>'warriors#regional_stats'

  resources :feedbacks

  resources :sessions

  resources :cabins

  resources :warriors do
    resources :address
  end

  root :to => 'warriors#index'

  match ':controller(/:action(/:id))(.:format)'
end

app/models/cabin.rb
class Cabin < ActiveRecord::Base
  attr_accessible :district,:state, :cabin_no, :vacant
  has_many :sessions

  def self.vacant_cabins
    where(:vacant=>true)
  end

  def pretty_cabin_name
    "#{self.cabin_no}"+" / "+"#{self.district}"+" / "+"#{self.state}"
  end

end

app/controllers/cabins_controller.rb
class CabinsController < ApplicationController
  # GET /cabins
  # GET /cabins.json
  def index
    @cabins = Cabin.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @cabins }
    end
  end

  # GET /cabins/1
  # GET /cabins/1.json
  def show
    @cabin = Cabin.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @cabin }
    end
  end

  # GET /cabins/new
  # GET /cabins/new.json
  def new
    @cabin = Cabin.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cabin }
    end
  end

  # GET /cabins/1/edit
  def edit
    @cabin = Cabin.find(params[:id])
  end

  # POST /cabins
  # POST /cabins.json
  def create
    @cabin = Cabin.new(params[:cabin])
    @cabin.vacant=true

    respond_to do |format|
      if @cabin.save
        format.html { redirect_to @cabin, notice: 'Cabin was successfully created.' }
        format.json { render json: @cabin, status: :created, location: @cabin }
      else
        format.html { render action: "new" }
        format.json { render json: @cabin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /cabins/1
  # PUT /cabins/1.json
  def update
    @cabin = Cabin.find(params[:id])

    respond_to do |format|
      if @cabin.update_attributes(params[:cabin])
        format.html { redirect_to @cabin, notice: 'Cabin was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @cabin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cabins/1
  # DELETE /cabins/1.json
  def destroy
    @cabin = Cabin.find(params[:id])
    @cabin.destroy

    respond_to do |format|
      format.html { redirect_to cabins_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/cabins_helper.rb
module CabinsHelper
end

app/views/cabins/_form.html.erb
<%= form_for @cabin, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :cabin_no, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :cabin_no, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :district, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :district, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :state, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :state, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                cabins_path, :class => 'btn' %>
  </div>
<% end %>

app/views/cabins/edit.html.erb
<%- model_class = Cabin -%>
<div class="page-header">
  <h3><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h3>
</div>
<%= render :partial => 'form' %>

app/views/cabins/index.html.erb
<%- model_class = Cabin -%>
<div class="page-header">
  <h2>Prayer Cabin Information<br><small>Intercessory Prayer Center </small></h2>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:cabin_no) %></th>
      <th><%= model_class.human_attribute_name(:district) %></th>
      <th><%= model_class.human_attribute_name(:state) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @cabins.each do |cabin| %>
      <tr>
        <td><%= link_to cabin.cabin_no , cabin_path(cabin) %></td>
        <td><%= cabin.district %></td>
        <td><%= cabin.state %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_cabin_path(cabin), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      cabin_path(cabin),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_cabin_path,
            :class => 'btn btn-primary' %>

app/views/cabins/new.html.erb
<%- model_class = Cabin -%>
<div class="page-header">
  <h3><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h3>
</div>
<%= render :partial => 'form' %>

app/views/cabins/show.html.erb
<%- model_class = Cabin -%>
<div class="page-header">
  <h3><%=t '.title', :default => model_class.model_name.human %></h3>
</div>

<table class="table">
  <td><strong><%= model_class.human_attribute_name(:cabin_no) %>:</strong></td>
  <td><%= @cabin.cabin_no %></td>
  <td><strong><%= model_class.human_attribute_name(:district) %>:</strong></td>
  <td><%= @cabin.district %></td>
  <td><strong><%= model_class.human_attribute_name(:state) %>:</strong></td>
  <td><%= @cabin.state %></td>
  <td><strong>Sessions:</strong></td>
  <td><%= @cabin.sessions.length %></td>
</table>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              cabins_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_cabin_path(@cabin), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              cabin_path(@cabin),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger' %>
</div>