config/routes.rb
IpcPcMgmt::Application.routes.draw do

  match 'warriors/list' => 'warriors#list'
  match 'sessions/list' => 'sessions#list'
  match 'sessions/end_session'=>'sessions#end_session'
  match 'sessions/warrior_sessions'=>'sessions#warrior_sessions'
  match 'sessions/statistics'=> 'sessions#statistics'
  match 'warriors/regional_stats'=>'warriors#regional_stats'

  resources :feedbacks

  resources :sessions

  resources :cabins

  resources :warriors do
    resources :address
  end

  root :to => 'warriors#index'

  match ':controller(/:action(/:id))(.:format)'
end

app/models/warrior.rb
class Warrior < ActiveRecord::Base

  has_one :address
  belongs_to :region
  has_many :sessions

  accepts_nested_attributes_for :address
  attr_accessible :church, :name, :phone, :referrer, :warrior_no,:region_id, :address_attributes, :commitment

  before_destroy :delete_address
  after_destroy :update_region_count
  before_create :generate_warrior_no
  after_create :update_region_count

  def self.search(search)
    if search
      where('name LIKE ? OR phone LIKE ? OR church LIKE ?', "%#{search}%","%#{search}%","%#{search}%")
    else
      scoped
    end
  end

  def self.todays_warriors
    Warrior.select("id,name,phone").where("commitment=?",Date.today.wday+1)
  end
  def self.tomorrows_warriors
    Warrior.select("id,name,phone").where("commitment=?",(Date.today.wday+2).modulo(8))
  end
  def self.day_after_tomorrows_warriors
    Warrior.select("id,name,phone").where("commitment=?",(Date.today.wday+3).modulo(8))
  end

  #converts numeric commitment to string
  def prayer_commitment
    comm={-1 => "No Commitments",0=>"Monthly",1=>"Every Sunday",2=>"Every Monday",3=>"Every Tuesday",4=>"Every Wednesday",5=>"Every Thursday",6=>"Every Friday",7=>"Every Saturday"}
    if self.commitment.nil?
      return "No Commitments"
    else
      return comm[self.commitment]
    end
  end

  def no_of_sessions
    self.sessions.length
  end
    def delete_address
      self.address.destroy
    end

    def generate_warrior_no
      region=self.region
      self.warrior_no="JM#{region.code}#{region.last_id+1}"
      region.last_id+=1
      region.save
    end

    def update_region_count
      self.region.update_count
    end


end

app/controllers/warriors_controller.rb
class WarriorsController < ApplicationController
  # GET /warriors
  # GET /warriors.json
  helper_method :sort_column, :sort_direction

  def index
    @regions=Region.all
    @today=Warrior.todays_warriors
    @tomorrow=Warrior.tomorrows_warriors
    @day_after=Warrior.day_after_tomorrows_warriors
  end

  def list
    if params[:region]!="" && !params[:region].nil?
      @region=Region.find(params[:region])
      @warriors = Warrior.where(:region_id=>@region.id)
    else
      @region=nil
      @warriors=Warrior.scoped
    end

    @warriors = @warriors.search(params[:search]).order(sort_column+ ' ' + sort_direction).paginate(:per_page => 20, :page => params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.js
      format.json { render json: @warriors }
    end
  end

  # GET /warriors/1
  # GET /warriors/1.json
  def show
    @warrior = Warrior.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @warrior }
    end
  end

  # GET /warriors/new
  # GET /warriors/new.json
  def new
    @warrior = Warrior.new
    @warrior.build_address
    @regions=Region.all
    @warrior_region=nil
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @warrior }
    end
  end

  # GET /warriors/1/edit
  def edit
    @warrior = Warrior.find(params[:id])
    @regions=Region.all
    @warrior_region=@warrior.region.id
  end

  # POST /warriors
  # POST /warriors.json
  def create
    @warrior = Warrior.new(params[:warrior])

    respond_to do |format|
      if @warrior.save
        format.html { redirect_to @warrior, notice: 'Warrior was successfully created.' }
        format.json { render json: @warrior, status: :created, location: @warrior }
      else
        format.html { render action: "new" }
        format.json { render json: @warrior.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /warriors/1
  # PUT /warriors/1.json
  def update
    @warrior = Warrior.find(params[:id])

    respond_to do |format|
      if @warrior.update_attributes(params[:warrior])
        format.html { redirect_to @warrior, notice: 'Warrior was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @warrior.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /warriors/1
  # DELETE /warriors/1.json
  def destroy
    @warrior = Warrior.find(params[:id])
    @warrior.destroy
    respond_to do |format|
      format.html { redirect_to warriors_url }
      format.json { head :no_content }
    end
  end

  def regional_stats
    @regions=Region.all
  end

 private
  def sort_column
    params[:sort] || "name"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ?  params[:direction] : "asc"
  end
end

app/helpers/warriors_helper.rb
module WarriorsHelper
end

app/views/warriors/_form.html.erb
<%= form_for @warrior, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field span4', :required=>"true" %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :church, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :church, :class => 'text_field span4' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :phone, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :phone, :class => 'text_field span4', :required=>"true" %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :referrer, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :referrer, :class => 'text_field span4' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :region_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.select :region_id, options_from_collection_for_select(@regions, "id", "name",:selected=>@warrior_region), { :style=>"width:250px"  ,:class=>"chzn-select"}%>
    </div>
  </div>
  <hr>
  <div class="control_group">
    <%= f.fields_for :address do |form| %>
      <%= form.label :address, :class => 'control-label' %>
      <div class="controls controls-row">
        <%= form.text_field :addr_1, :class=> 'text_field span4',:placeholder=>"Address Line 1" %>
        <br><br>
        <%= form.text_field :addr_2, :class=> 'text_field span4',:placeholder=>"Address Line 2" %>
        <br><br>
        <%= form.text_field :city, :class=> 'text_field span2',:placeholder=>"City" %>
        <%= form.text_field :pin_code, :class=> 'text_field span2',:placeholder=>"Pin Code" %>
        <br><br>
        <%= form.text_field :country, :class=> 'text_field span3',:placeholder=>"Country" %>
    <%end%>
  </div>
  <hr>
    <div class="control-group">
    <%= f.label "Prayer Commitment", :class => 'control-label' %>
    <div class="controls">
      <%= f.select :commitment,
       options_for_select([["No Commitments",-1],
                           ["Monthly",0],
                           ["Every Sunday",1],
                           ["Every Monday",2],
                           ["Every Tuesday",3],
                           ["Every Wednesday",4],
                           ["Every Thursday",5],
                           ["Every Friday",6],
                           ["Every Saturday",7] ],:selected=>@warrior.commitment)
      %>
    </div>
  </div>



  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to "Cancel",
                :back,:id=>@warrior.id, :class => 'btn' %>
  </div>
<% end %>

<script>
$(document).ready(function(){

  $("#warrior_region_id").attr("class","chzn-select");
  $("#warrior_region_id").attr("style","width:250px");
  $("#warrior_region_id").attr("data-placeholder","Choose Region");
});
</script>

app/views/warriors/_warriors.html.erb
<table class="table table-nonfluid">
<tr>
  <th>Name</th>
  <th>Phone Number</th>
</tr>
<% if !warriors.nil? %>
  <%for warrior in warriors %>
    <tr>
      <td><%=link_to warrior.name, warrior_path(warrior) %></td>
      <td><%=warrior.phone%></td>
    </tr>
  <%end%>
<%else%>
  <tr><td colspan="2"> No Warriors Scheduled for Today</td></tr>
<%end%>
</table>

app/views/warriors/_warriors_list.html.erb
<table class="table table-condensed table-striped">
  <thead>
    <tr>
      <th><%= sortable "name"%></th>
      <th><%= sortable "warrior_no"%></th>
      <th><%= sortable "church",nil%></th>
      <th><%= "Phone" %></th>
      <th>Region</th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @warriors.each do |warrior| %>
      <tr>
        <td><%= warrior.name %></td>
        <td><%= warrior.warrior_no %></td>
        <td><%= warrior.church %></td>
        <td><%= warrior.phone %></td>
        <td><%= warrior.region.name %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      warrior_path(warrior),:method => :get, :class => 'btn btn-mini' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_warrior_path(warrior), :class => 'btn btn-mini' %>

        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @warriors,:renderer => BootstrapPagination::Rails %>

app/views/warriors/edit.html.erb
<%- model_class = Warrior -%>
<div class="page-header">
  <h3><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h3>
</div>
<%= render :partial => 'form' %>

app/views/warriors/index.html.erb
<div class="page-header"><h2>Prayer Warriors</h2></div>
<div class="row">
<div class="span4">
<h4>View Prayer Warriors List:</h4>
<br>
<%= form_tag warriors_list_path, :class=>"form form-inline ",:method=>"get" do -%>
      <p>
      <select  data-placeholder="Choose Region" style="width:250px"  name="region" class="chzn-select">
        <option value=""></option>
        <% for region in @regions %>
          <%= raw("<option value='#{region.id}'>#{region.name}</option>") %>
        <%end%>
      </select>
      </p>
      <%= submit_tag "View Prayer Warriors", :class=>"btn" %>
<% end %>
</div>
<div class="span4 pull-right">
<h4>Search Prayer Warriors:</h4>
<br>
<%= form_tag url_for(:controller=>:warriors,:action=>:list), :method => 'get',:class=>"form-search",:id=>"warriors_search_index" do %>
  <p>
    <%= text_field_tag :search, params[:search],:class=>"input",:placeholder=>"Name / Phone / ID" %></p>
    <%= submit_tag "Search", :name => nil,:class=>"btn" %>

<% end %>

</div>
</div>
<hr>
<div class="row">
<div class="span6 offset2">
<h5>Prayer Warriors Scheduled to pray in coming days:</h5>
<div class="tabbable"> <!-- Only required for left/right tabs -->
      <ul class="nav nav-tabs">
        <li class="active"><a href="#today" data-toggle="tab">Today</a></li>
        <li><a href="#tomorrow" data-toggle="tab">Tomorrow</a></li>
        <li><a href="#day_after" data-toggle="tab">Day after Tomorrow</a></li>
      </ul>
      <div class="tab-content" id="sessions_tabs">
        <div class="tab-pane active" id="today">
          <%= render :partial=>'warriors',:locals=>{:warriors=>@today} %>
        </div>
        <div class="tab-pane" id="tomorrow">
          <%= render :partial=>'warriors',:locals=>{:warriors=>@tomorrow} %>
        </div>
        <div class="tab-pane" id="day_after">
          <%= render :partial=>'warriors',:locals=>{:warriors=>@day_after} %>
        </div>
      </div>
    </div>
</div>
</div>
<hr> <div class="row">
<div class="span6 offset2">
<%= link_to "New Prayer Warrior",
            new_warrior_path,
            :class => 'btn btn btn-primary pull-left' %> &nbsp;&nbsp;
<%= link_to "Regional Statistics",
            warriors_regional_stats_path,
            :class => 'btn ' %>
</div></div>

<br>
<br>
<br>

app/views/warriors/list.html.erb
<%- model_class = Warrior -%>
<div class="page-header">
  <h3>Prayer Warriors<br><small><%= @region.name unless @region.nil?%></small></h3>
</div>

<div class="row">
<div class="span3 pull-left"><h5>Totall Warriors: <%= @warriors.length %> </h5></div>
<div class="span3 pull-right">
<%= form_tag url_for(:controller=>:warriors,:action=>:list), :method => 'get',:class=>"form-search pull-right",:id=>"warriors_search" do %>

    <%= text_field_tag :search, params[:search],:class=>"input-medium search-query", :placeholder=>"Name / Phone / ID" %>
    <%= submit_tag "Search", :name => nil,:class=>"btn" %>
    <%= hidden_field_tag :direction, sort_direction %>
    <%= hidden_field_tag :sort, sort_column %>
    <%= hidden_field_tag :region, @region.id unless @region.nil?%>
<% end %>
</div>
</div>


<div id="warriors">
  <%= render 'warriors_list' %>

</div>
<div class="form-actions">
<%= link_to "Back", url_for(:controller=>"warriors",:action=>"index"), :class=>"btn"%>
<%= link_to "New Prayer Warrior",
            new_warrior_path,
            :class => 'btn btn btn-primary' %>
</div>

app/views/warriors/list.js.erb
$("#warriors").html('<%= escape_javascript(render("warriors_list") ) %>');

app/views/warriors/new.html.erb
<%- model_class = Warrior -%>
<div class="page-header">
  <h3>New Prayer Warrior</h3>
</div>
<%= render :partial => 'form' %>

app/views/warriors/regional_stats.html.erb
<div class="page-header">
  <h3>Regional Statistics</h3>
</div>

<br>

<table class="table table-striped">
  <thead>
  <tr>
    <th>Region</th>
    <th>Prayer Warriors</th>
  </tr>
  </thead>
  <tbody>
  <%for region in @regions %>
    <tr>
      <td><%= region.name+" / "+region.code %></td>
      <td><%=region.warriors.length %></td>
    </tr>
  <%end%>
  </tbody>
</table>
<hr>
<%= link_to "Back",warriors_path,:class=>"btn" %>

app/views/warriors/show.html.erb
<%- model_class = Warrior -%>
<div class="page-header">
  <h3>Prayer Warrior</h3>
</div>
<legend><strong><%= @warrior.name %></strong></legend>
<table class="table table-striped">
  <tr>
  <th><strong><%= model_class.human_attribute_name(:warrior_no) %>:</strong></th>
  <td><%= @warrior.warrior_no %></td>
  </tr>
    <tr>
      <th rowspan="4">Address:</th>
      <td><%= @warrior.address.addr_1 %></td>
      <tr>
        <td><%= @warrior.address.addr_2 %></td>
      </tr>
      <tr>
        <td><%= @warrior.address.city %> | Pin-code: <%= @warrior.address.pin_code %> </td>
      </tr>
      <tr>
        <td><%= @warrior.address.country %></td>
      </tr>
    </tr>
  <tr>
    <th><strong><%= model_class.human_attribute_name(:church) %>:</strong></th>
    <td><%= @warrior.church %></td>
  </tr>
  <tr>
  <th><strong><%= model_class.human_attribute_name(:phone) %>:</strong></th>
  <td><%= @warrior.phone %></td>
  </tr>
  <tr>
  <th><strong><%= model_class.human_attribute_name(:referrer) %>:</strong></th>
  <td><%= @warrior.referrer %></td>
  </tr>
  <th><strong>Prayer Commitment:</strong></th>
  <td><%= @warrior.prayer_commitment %></td>
  </tr>

</table>
<hr>
<div class="well">
  <h5>Prayer Sessions</h5>
  <br>
  <p><%= link_to "Start a new Session", new_session_path({:warrior=>@warrior.id}),:class=>"btn btn-primary" %>&nbsp;&nbsp;<%= link_to "View Sessions", url_for(:controller=>"sessions",:action=>"warrior_sessions",:warrior=>@warrior.id), :class=>"btn btn-primary" %></p>
</div>
<br>
<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              warriors_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_warrior_path(@warrior), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              warrior_path(@warrior),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger' %>
</div>