config/routes.rb
IpcPcMgmt::Application.routes.draw do

  match 'warriors/list' => 'warriors#list'
  match 'sessions/list' => 'sessions#list'
  match 'sessions/end_session'=>'sessions#end_session'
  match 'sessions/warrior_sessions'=>'sessions#warrior_sessions'
  match 'sessions/statistics'=> 'sessions#statistics'
  match 'warriors/regional_stats'=>'warriors#regional_stats'

  resources :feedbacks

  resources :sessions

  resources :cabins

  resources :warriors do
    resources :address
  end

  root :to => 'warriors#index'

  match ':controller(/:action(/:id))(.:format)'
end

app/models/feedback.rb
class Feedback < ActiveRecord::Base
  attr_accessible :feedback, :session_id
  belongs_to :session
end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController
  # GET /feedbacks
  # GET /feedbacks.json
  def index
    @feedbacks = Feedback.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @feedbacks }
    end
  end

  # GET /feedbacks/1
  # GET /feedbacks/1.json
  def show
    @feedback = Feedback.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @feedback }
    end
  end

  # GET /feedbacks/new
  # GET /feedbacks/new.json
  def new
    @feedback = Feedback.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @feedback }
    end
  end

  # GET /feedbacks/1/edit
  def edit
    @feedback = Feedback.find(params[:id])
  end

  # POST /feedbacks
  # POST /feedbacks.json
  def create
    @feedback = Feedback.new(params[:feedback])

    respond_to do |format|
      if @feedback.save
        format.html { redirect_to @feedback.session, notice: 'Feedback was successfully created.' }
        format.json { render json: @feedback, status: :created, location: @feedback }
      else
        format.html { render action: "new" }
        format.json { render json: @feedback.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /feedbacks/1
  # PUT /feedbacks/1.json
  def update
    @feedback = Feedback.find(params[:id])

    respond_to do |format|
      if @feedback.update_attributes(params[:feedback])
        format.html { redirect_to @feedback, notice: 'Feedback was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @feedback.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /feedbacks/1
  # DELETE /feedbacks/1.json
  def destroy
    @feedback = Feedback.find(params[:id])
    @feedback.destroy

    respond_to do |format|
      format.html { redirect_to feedbacks_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/views/feedbacks/_form.html.erb
<%= form_for @feedback, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :session_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :session_id, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :feedback, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :feedback, :class => 'text_area' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                feedbacks_path, :class => 'btn' %>
  </div>
<% end %>

app/views/feedbacks/edit.html.erb
<%- model_class = Feedback -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/feedbacks/index.html.erb
<%- model_class = Feedback -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:session_id) %></th>
      <th><%= model_class.human_attribute_name(:feedback) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @feedbacks.each do |feedback| %>
      <tr>
        <td><%= link_to feedback.id, feedback_path(feedback) %></td>
        <td><%= feedback.session_id %></td>
        <td><%= feedback.feedback %></td>
        <td><%=l feedback.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_feedback_path(feedback), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      feedback_path(feedback),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_feedback_path,
            :class => 'btn btn-primary' %>

app/views/feedbacks/new.html.erb
<%- model_class = Feedback -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/feedbacks/show.html.erb
<%- model_class = Feedback -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:session_id) %>:</strong></dt>
  <dd><%= @feedback.session_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:feedback) %>:</strong></dt>
  <dd><%= @feedback.feedback %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              feedbacks_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_feedback_path(@feedback), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              feedback_path(@feedback),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger' %>
</div>