config/routes.rb
IpcPcMgmt::Application.routes.draw do

  match 'warriors/list' => 'warriors#list'
  match 'sessions/list' => 'sessions#list'
  match 'sessions/end_session'=>'sessions#end_session'
  match 'sessions/warrior_sessions'=>'sessions#warrior_sessions'
  match 'sessions/statistics'=> 'sessions#statistics'
  match 'warriors/regional_stats'=>'warriors#regional_stats'

  resources :feedbacks

  resources :sessions

  resources :cabins

  resources :warriors do
    resources :address
  end

  root :to => 'warriors#index'

  match ':controller(/:action(/:id))(.:format)'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "IpcPcMgmt" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->
    <%= javascript_include_tag "application" %>
    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'images/favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>

    <div class="navbar navbar-fixed-top ">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/" style='font-size:18px'>Prayer Warriors & Cabins Manager</a>
          <div class="container nav-collapse">
            <ul class="nav">
              <li id="nav_warriors"><%= link_to "Prayer Warriors", warriors_path %></li>
              <li id="nav_sessions"><%= link_to "Prayer Sessions", sessions_path %></li>
              <li id="nav_cabins"><%= link_to "Cabin Info", cabins_path %></li>
              <li id="nav_cabins">
                <%= login_or_logout %>
              </li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
      <div class="content">
        <div class="row">
           <div class="span10 offset1" id="content">
           <% flash.each do |name, msg| %>
              <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
                <a class="close" data-dismiss="alert">&#215;</a>
                <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
              </div>
            <% end %>
              <%= yield %>
            </div>
        </div><!--/row-->
      </div><!--/content-->


    </div> <!-- /container -->

    <div class="navbar navbar-fixed-bottom navbar-inverse">
      <div class="navbar-inner-bottom">
        <div class="container">
          <center><p style="color: #FFFFFF; font-size: 12px; vertical-align:middle; line-height: 12px; margin-bottom: 0px;padding: 5px;">&copy; Jesus Meets Ministries - Intercessory Prayer Center</p></center>

        </div>
      </div>
    </div>

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->

    <script>
      $(document).ready(function(){
        $('#nav li').removeAttr("class");
        $(<%= raw("'#nav_#{@current_controller}'")%>).attr("class","active");
      });
    </script>

  </body>
</html>